# Application Name
spring.application.name=School Management System

# Database Configuration
spring.config.import=optional:file:.env[.properties]
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_username}
spring.datasource.password=${DB_password}

springdoc.swagger-ui.path=/swagger
springdoc.api-docs.path=/api-docs