# Load .env file using spring-dotenv
spring.config.import=optional:file:.env[.properties]


# Application Name
spring.application.name=School Management System

# Database Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_username}
spring.datasource.password=${DB_password}

# JWT Configuration
jwt.secret=${JWT_SECRET}


# swagger configuration
springdoc.swagger-ui.path=/api/swagger
springdoc.api-docs.path=/api-docs