# Application Name
spring.application.name=School Management System

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/SMS
spring.datasource.username=schoolManager
spring.datasource.password=schoolManager@123456
